### PR TITLE
Updating for v2.0.2

### PR DESCRIPTION
**Pull request by garethtdavies**

### CODE REVIEW

**Comment by karel-3d** [comment]
I will probably add you commit rights here :)

**Comment by karel-3d** [comment]
hm I added you as a collaborator but maybe I could have just added you to the group...

**Comment by garethtdavies** [comment]
Great, thanks. I actually think that's the easiest way 👍

**Comment by karel-3d** [comment]
You should now be in the group, do whatever you want with the repo :)

**Pull request merged**
